apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tourismgoal-com
  namespace: default
spec:
  secretName: tourismgoal-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tourismgoal.com
  dnsNames:
  - tourismgoal.com
  
