additionalArguments:
 - --certificatesresolvers.acme-dns.acme.dnschallenge.provider=acme-dns
 - --certificatesresolvers.acme-dns.acme.email=admin@securedsoft.online
 - --certificatesresolvers.acme-dns.acme.storage=/ssl-certs/acme-dns.json

logs:
# Configure log settings here...
  general:
    level: ERROR

ports:
# Configure your entrypoints here...
  web:
    # (optional) Permanent Redirect to HTTPS
    redirectTo: 
       port: websecure
  websecure:
    tls:
      enabled: true
      # (optional) Set a Default CertResolver
      certResolver: acme-dns
  

env:

  - name: ACME_DNS_API_BASE
    valueFrom:
      secretKeyRef:
        key: apiUrl
        name: acme-dns-credentials
  - name: ACME_DNS_STORAGE_PATH
    valueFrom:
      secretKeyRef:
        key: storagePath
        name: acme-dns-credentials

# Disable Dashboard
ingressRoute:
  dashboard:
    enabled: false

# Persistent Storage
persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

deployment:
  initContainers:
    # The "volume-permissions" init container is required if you run into permission issues.
    # Related issue: https://github.com/containous/traefik/issues/6972
    
    - name: volume-permissions
      image: busybox:1.31.1
      command:
        [
          "sh",
          "-c",
          "touch /ssl-certs/acme-dns.json; chown 65532 /ssl-certs/acme-dns.json; chmod -v 600 /ssl-certs/acme-dns.json",
        ]
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs

# Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
ingressClass:
  enabled: true
  isDefaultClass: true
