apiVersion: apps/v1
kind: Deployment
metadata:
  name: iecbd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iecbd
  template:
    metadata:
      labels:
        app: iecbd
    spec:
      containers:
      - name: iecbd
        image: larrylinus/securedsoft:iecbd-latest
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name:  iecbd
  namespace: applications
spec:
  selector:
    app:  iecbd
  
  type:  ClusterIP
  ports:
  - name:  http
    port:  3000 

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iecbd # Name of the ingress object
  namespace: applications # Name of the namespace
spec:
  rules:
  - host: "iecbd.securedsoft.online"  # Your hostname
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iecbd  # The name of the service
            port:
              number: 3000  # Service Portnumber
