apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: larrylinus/securedsoft:linux
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name:  blog
  namespace: applications
spec:
  selector:
    app:  blog
  
  type:  ClusterIP
  ports:
  - name:  http
    port:  3000 

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog # Name of the ingress object
  namespace: applications # Name of the namespace
spec:
  rules:
  - host: "site.securedsoft.online"  # Your hostname
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog  # The name of the service
            port:
              number: 3000  # Service Portnumber
