version: '2.1'

services:
  traefik:
    image: larrylinus/securedsoft:iecbd-latest
    container_name: iecbd
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 3000:3000
      
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.iecbd-secure.entrypoints=websecure"
      - "traefik.http.routers.iecbd-secure.rule=Host(`iecbd.securedsoft.online`)"
      
      
networks:
  proxy:
    external: true
