apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdmarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdmarket
  template:
    metadata:
      labels:
        app: bdmarket
    spec:
      containers:
      - name: bdmarket
        image: larrylinus/securedsoft:bdmarket-menual
        # resources:
        #     limits:
        #       memory: "4Gi"
        #       cpu: "4000m"
        #     requests:
        #       memory: "2Gi"
        #       cpu: "2000m"
        
---

apiVersion: v1
kind: Service
metadata:
  name:  bdmarket
  namespace: applications
spec:
  selector:
    app:  bdmarket
  
  type:  ClusterIP
  ports:
  - name:  http
    port:  3000 

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bdmarket # Name of the ingress object
  namespace: applications # Name of the namespace
spec:
  rules:
  - host: "bdmarket.securedsoft.online"  # Your hostname
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bdmarket  # The name of the service
            port:
              number: 3000  # Service Portnumber
