apiVersion: apps/v1
kind: Deployment
metadata:
  name: securedsoft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securedsoft
  template:
    metadata:
      labels:
        app: securedsoft
    spec:
      containers:
      - name: securedsoft
        image: larrylinus/securedsoft:securedsoft-website
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name:  securedsoft
  namespace: applications
spec:
  selector:
    app:  securedsoft
  
  type:  ClusterIP
  ports:
  - name:  http
    port:  3000 

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: securedsoft # Name of the ingress object
  namespace: applications # Name of the namespace
spec:
  rules:
  - host: "securedsoft.net"  # Your hostname
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: securedsoft  # The name of the service
            port:
              number: 3000  # Service Portnumber
  - host: "www.securedsoft.net"  # Your hostname
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: securedsoft  # The name of the service
            port:
              number: 3000